### PR TITLE
Completely separate Jupyter mode and Vim mode

### PR DESCRIPTION
**Pull request by lambdalisue**
Screencast

Several users suggested me to eliminate Jupyter mode #27 
I was/am completely agree with that having tightly connected three mode (Jupyter mode, Command mode, and Insert mode) makes users confused.

However, not all manipulation can be executed on Vim's command mode while we have only two modifier keys (Shift or Ctrl) and a lot of key combination is taken.

So that I decide to separate Jupyter and Vim as much as possible to use a different key mapping to escape the mode. So from this PR, the behavior and concept of this extension will drastically change.
### Concept
- Jupyter mode stands for doing complex manipulation
- Command mode (Vim) stands for
  - Command mode for CodeMirror.Vim
  - Command mode for Jupyter
- Insert mode (Vim) stands for text manipulation

To achieve this concept, the following changes were performed.
- You can easily enter Vim mode with 1) double clicking, 2) `<Enter>`, or 3) `i`
- You need to hit `<Shift-Esc>`, a key combination which is difficult to hit, to leave from Vim mode
- I assumed that there are three types of keys should be in Command mode
  - Misc keys, which stands for to run code, show panel, or any kind of features which are not really Vim like. Most of misc keys are only in Jupyter mode
  - Repeat keys (not sure for naming :-p), which users would repeat, like `j/k` or `Ctrl-y/e`. Most of keys are existing both mode with `Ctrl` or `Ctrl-Shift` prefix like `Ctrl-j/l` select next/previous cells, `Ctrl-Shift-k/j` extend the selection. Additionaly, bare keys like `j/k` are provided in Jupyter mode
  - Onetime keys, which user usually hit just onetime. In Jupyter mode, these keys are mapped naturally like `g,g` select a first cell. In Vim mode, all keys are privided with `<C-o>` prefix (like `<C-o>` in insert mode of native Vim). So that `<C-o>gg` select a first cell and re-enter the Vim mode.
- No Jupyter related mappings are allowed in Insert mode

These mappings aim to force users to stay in Vim mode as long as possible. So from this commit, jupyter-vim-binding assumed that user stays in Vim mode much more than Jupyter mode.
**You can check most of these mappings by hitting `F1` in Jupyter like Vim** or read the source code around
- [Edit (Vim) mode](https://github.com/lambdalisue/jupyter-vim-binding/blob/feature/eliminate_jupyter_command_mode/vim_binding.js#L375)
- [Command (Jupyter) mode](https://github.com/lambdalisue/jupyter-vim-binding/blob/feature/eliminate_jupyter_command_mode/vim_binding.js#L425)
### Need feedback

I think I like this new behavior and this should be a next release. **So give me your feedback!**
I think I will release this new version when I finish writing the README and fix bugs reported from you guys ;-)

### CODE REVIEW

**Comment by jhrmnn** [comment]
This is perfect! I've been using it since morning and find it delicious to work with.

**Comment by lambdalisue** [comment]
Done. Let me know if you find some stupid points, both in code or documents.

**Comment by lambdalisue** [comment]
@azag0 Thanks for feedback ;-) Let me know if you find any unwilling behaviour or wrong documents

**Comment by giulioungaretti** [comment]
amaze! works prefect for now.  fantastic job !

**Comment by lambdalisue** [comment]
@giulioungaretti Thanks for feedback ;-)

**Comment by lambdalisue** [comment]
I've been using this one and find that this is really useful.
Without any negative feedback, I think I'll update the master to this one in this weekend.

**Comment by giulioungaretti** [comment]
Same, it’s just the way it supposed to be IMHO.

I’d say go and merge :D

**Comment by lambdalisue** [comment]
Now jupyter-vim-binding provide the following `<Plug>` mappings for CodeMirror.
- `<Plug>(vim-binding-j)` : `j` which move to the next cell at the cell side
- `<Plug>(vim-binding-k)` : `k` which move to the previous cell at the cell side
- `<Plug>(vim-binding-gj)` : `gj` which move to the next cell at the cell side
- `<Plug>(vim-binding-gk)` : `gk` which move to the previous cell at the cell side
- `<Plug>(vim-binding-+)` : `+` which move to the next cell at the cell side
- `<Plug>(vim-binding--)` : `-` which move to the previous cell at the cell side
- `<Plug>(vim-binding-_)` : `_` which move to the next cell at the cell side

While CodeMirror's Vim does not provide `noremap` type of mappings.
You need to use these `<Plug>` mappings to prevent infinity loop like:

``` javascript
// Configure CodeMirror
require([
  'nbextensions/vim_binding/vim_binding',   // depends your installation
], function() {
  // Swap j/k and gj/gk (Note that <Plug> mappings)
  CodeMirror.Vim.map("j", "<Plug>(vim-binding-gj)", "normal");
  CodeMirror.Vim.map("k", "<Plug>(vim-binding-gk)", "normal");
  CodeMirror.Vim.map("gj", "<Plug>(vim-binding-j)", "normal");
  CodeMirror.Vim.map("gk", "<Plug>(vim-binding-k)", "normal");
});
```

**Comment by lambdalisue** [comment]
Now jupyter-vim-binding support `<C-n>/<C-p>` completion and `<C-g>` tooltip which show something like below

selection_002

**Comment by giulioungaretti** [comment]
This is fantastic 🍾🍾🍾🍾🍾

**Comment by lambdalisue** [comment]
<del>Tooltip feature is [under discussion](https://github.com/jupyter/notebook/issues/167#issuecomment-114587195) in Jupyter while they are not sure which is the best way to show the tooltip. However, we are Vimmer so I think `<C-g>`; which show a current line and file information in native Vim; is a perfect mapping for us ;-)</del>

It seems `Shift-Tab` works. My bad. But `<C-g>` is more natural for us I think ;-)

**Comment by lambdalisue** [comment]
Hum... It seems that `<C-o>G` or any key mappings which requires `Shift` after `<C-o>` is not working

**Comment by lambdalisue** [comment]
Fixed :-]

**Comment by petergthatsme** [comment]
it seems like since [https://github.com/lambdalisue/jupyter-vim-binding/commit/6eb8f24eb458e68125f99c1acd13c7bcc2e478f7] the plugin does not work on my machine.. it looks like this is where you dropped the "old jupyter support". The effects is that the shortcuts don't load (i.e. so alt-enter, etc are broken)

I'm running:
jupyter (1.0.0)
jupyter-client (4.1.1)
jupyter-console (4.0.3)
jupyter-core (4.0.6)

Which version is then supported as of the latest patch in this branch? Could be good to update the docs with this info once it goes live.

,... and thanks again for your all work - even running the version before this change, which already includes the cell jumping in vim normal mode with j/k is a tremendous improvement in usability!

**Comment by lambdalisue** [comment]
@petergthatsme 
This is my `pip freeze` result

```
jupyter==1.0.0
jupyter-client==4.1.1
jupyter-console==4.1.0
jupyter-core==4.0.6
```

So it is a bit different. Try `pip install jupyter --upgrade` ;-)

> Which version is then supported as of the latest patch in this branch? Could be good to update the docs with this info once it goes live.

Actually it should while you have `jupyter-client 4.1.1` but I'm not really sure about version of Jupyter... Them version is so complicated.

**Comment by petergthatsme** [comment]
yup thanks.. i've upgraded everything since the last msg. It does seem like that changes you made need a a newer jupyter-console.

**Comment by lambdalisue** [comment]
No idea why [jupyter-console](https://github.com/jupyter/jupyter_console) solves your problem. 

You may once installed jupyter from non PyPI repository I guess (like `pip install https://github.com/jupyter/jupyter#egg=jupyter`)
Then your local jupyter was not actually jupyter 1.0 or jupyter-client 4.1 and updating jupyter-console with `--upgrade` trigger to re-install correct version from PyPI.

Just guess. Or jupyter team might delete and re-update jupyter 1.0 or jupyter-client 4.1 with different one once.

**Comment by lambdalisue** [comment]
I think, I'm going to merge this branch into `master` **tomorrow morning (in JST)**.

**Let me know if you have negative feedbacks before that**, otherwise I'll kick off the users using old Jupyter by merging this branch into `master` while I couldn't be bothered to support ancient multiple versions :-p

Note that there is [`v0.1.0`](https://github.com/lambdalisue/jupyter-vim-binding/releases) which suppose to support Jupyter 4.0.x (IPython Notebook 4.0) in case someone really need it. But I'm not going to support that release any more.

**Comment by petergthatsme** [comment]
@lambdalisue 

On one of my machines this could have been the case (having an older jupyter installed before), but on the other one, unlikely ,as i did it recently from a clean os setup. 

One more suggestion I would propose, is to include the Ctrl+Enter and Shift+Enter shortcuts when in the vim input mode. This would let the user skip an extra Esc press when executing code after editing.

**Comment by lambdalisue** [comment]
Ok. I think this is a time to merge ;-)

**Comment by lambdalisue** [comment]
:tada:

**Pull request merged**
